### ISSUE TITLE
CSS Logical Properties

### ISSUE THREAD

**Issue by jlarmstrongiv** [shannonmoeller/reset-css#18]
[CSS Logical Properties](https://medium.com/@elad/new-css-logical-properties-bc6945311ce7), such as `margin-block-start`, are not overridden.  

Quick fix: 
```css
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed,
figure, figcaption, footer, header, hgroup,
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
	margin-block-start: 0;
	margin-block-end: 0;
	padding-block-start: 0;
	padding-block-end: 0;
	border-inline-start: 0;
	border-inline-end: 0;
}
```
